export const SAMPLE_JOBS = [
  {
    id: 1, filter: 'resort',
    badges: [{ c: 'new', t: 'New' }],
    icon: '🍽️', title: 'Head Chef — Asian Cuisine',
    co: 'Soneva Fushi', loc: 'Baa Atoll',
    type: 'Full-time', dept: 'Food & Beverage',
    sal: 'USD 2,800–3,500', salNote: '/mo + benefits', salVal: 3500,
    tags: ['Asian Cuisine', 'Kitchen Lead', '5-Star'], posted: '2h ago',
    desc: 'Lead a passionate kitchen team delivering exceptional Asian dining across three outlets. Design seasonal menus celebrating Maldivian-sourced ingredients, oversee food safety standards, and mentor junior chefs.',
    reqs: ['5+ years as Head Chef in luxury hospitality', 'Expertise in Japanese, Thai, and Indian cuisines', 'Experience managing teams of 10+', 'HACCP certification', 'Fluent English'],
  },
  {
    id: 2, filter: 'resort',
    badges: [{ c: 'hot', t: '🔥 Hot' }],
    icon: '🛎️', title: 'Front Office Manager',
    co: 'Anantara Maldives', loc: 'North Malé Atoll',
    type: 'Full-time', dept: 'Front Office',
    sal: 'USD 2,400–3,000', salNote: '/mo + accommodation', salVal: 3000,
    tags: ['Management', 'Opera PMS', 'Guest Relations'], posted: '5h ago',
    desc: 'Oversee all front office operations across our 80-villa resort. Lead a team of 12 guest service professionals, manage VIP arrivals, and drive NPS scores above 95.',
    reqs: ['Degree in Hospitality Management', '4+ years front office in a 5-star hotel', 'Opera PMS proficiency', 'Fluent English', 'Strong leadership under pressure'],
  },
  {
    id: 3, filter: 'resort',
    badges: [{ c: 'new', t: 'New' }],
    icon: '🤿', title: 'PADI Dive Instructor',
    co: 'Kandima Maldives', loc: 'Dhaalu Atoll',
    type: 'Full-time', dept: 'Diving & Water Sports',
    sal: 'USD 1,600–2,200', salNote: '/mo + tips', salVal: 2200,
    tags: ['PADI', 'Marine Conservation', 'Guest Facing'], posted: '8h ago',
    desc: 'Guide international guests through some of the world\'s most pristine reefs. Conduct discovery dives, PADI certification courses, and lead weekly coral restoration sessions.',
    reqs: ['PADI Divemaster or Instructor certification', '200+ logged dives', 'Rescue Diver & First Aid certified', 'Experience with international guests', 'Passion for marine conservation'],
  },
  {
    id: 4, filter: 'local',
    badges: [{ c: 'exp', t: '⏳ Closing Soon' }],
    icon: '💻', title: 'IT Systems Administrator',
    co: 'Bank of Maldives', loc: 'Malé',
    type: 'Full-time', dept: 'IT & Technology',
    sal: 'MVR 18,000–22,000', salNote: '/mo', salVal: 22000,
    tags: ['Network Admin', 'Cybersecurity', 'On-site'], posted: '1d ago',
    desc: 'Maintain and strengthen the bank\'s internal IT infrastructure, network systems, and cybersecurity posture. Support 500+ staff across multiple branches.',
    reqs: ['BSc in IT or Computer Science', '3+ years systems administration', 'Cisco CCNA or equivalent', 'Windows Server & Linux experience', 'Maldivian nationals preferred'],
  },
  {
    id: 5, filter: 'resort',
    badges: [{ c: 'new', t: 'New' }],
    icon: '💆', title: 'Ayurvedic Spa Therapist',
    co: 'Six Senses Laamu', loc: 'Laamu Atoll',
    type: 'Full-time', dept: 'Spa & Wellness',
    sal: 'USD 1,400–1,900', salNote: '/mo + accommodation', salVal: 1900,
    tags: ['Ayurveda', 'Luxury Spa', 'Wellness'], posted: '12h ago',
    desc: 'Deliver world-class Ayurvedic treatments using sustainably-sourced local products. Create bespoke wellness journeys for discerning international guests.',
    reqs: ['Diploma in Ayurvedic Therapy', '2+ years luxury spa experience', 'Swedish, Deep Tissue & Ayurvedic proficiency', 'Calm professional manner', 'English communication skills'],
  },
  {
    id: 6, filter: 'local',
    badges: [{ c: 'new', t: 'New' }],
    icon: '📈', title: 'Digital Marketing Executive',
    co: 'Villa Hotels & Resorts', loc: 'Malé',
    type: 'Full-time', dept: 'Sales & Marketing',
    sal: 'MVR 13,000–16,000', salNote: '/mo', salVal: 16000,
    tags: ['SEO', 'Meta Ads', 'Google Ads'], posted: '1d ago',
    desc: 'Drive digital presence for a leading Maldivian hospitality group. Manage social channels, paid campaigns, and content for 4 properties.',
    reqs: ['Degree in Marketing or Communications', '2+ years digital marketing experience', 'Proficiency in Meta Ads, Google Ads & SEO', 'Strong English and Dhivehi copywriting', 'Maldives tourism knowledge preferred'],
  },
  {
    id: 7, filter: 'resort',
    badges: [{ c: 'new', t: 'New' }, { c: 'feat', t: '⭐ Featured' }],
    icon: '🐠', title: 'Marine Biologist — Coral Restoration',
    co: 'Velaa Private Island', loc: 'Noonu Atoll',
    type: 'Full-time', dept: 'Marine Biology',
    sal: 'USD 2,000–2,800', salNote: '/mo + accommodation', salVal: 2800,
    tags: ['Conservation', 'Coral Restoration', 'Research'], posted: '3h ago',
    desc: 'Lead the marine conservation program: daily reef monitoring, coral transplantation, and educating ultra-luxury guests about ocean health.',
    reqs: ['BSc/MSc in Marine Biology or Marine Science', '2+ years field research experience', 'Advanced Open Water Scuba minimum', 'Coral transplantation experience', 'Excellent public speaking skills'],
  },
  {
    id: 8, filter: 'resort',
    badges: [{ c: 'exp', t: '⏳ Closing Soon' }],
    icon: '🎨', title: 'Kids Club Coordinator',
    co: 'Four Seasons Kuda Huraa', loc: 'North Malé Atoll',
    type: 'Full-time', dept: 'Kids Club',
    sal: 'USD 1,400–1,800', salNote: '/mo + accommodation', salVal: 1800,
    tags: ['Child Education', 'Activity Planning', 'Water Safety'], posted: '2d ago',
    desc: 'Design and run daily programmes for children aged 4–12 including environmental education, arts and crafts, and supervised snorkelling.',
    reqs: ['Diploma in Early Childhood Education', '2+ years working with children', 'Child First Aid certified', 'Swimming competency required', 'Creative, energetic, and patient'],
  },
  {
    id: 9, filter: 'maldivian',
    badges: [{ c: 'mv', t: '🇲🇻 MV Only' }],
    icon: '⚖️', title: 'Legal Officer',
    co: 'Ministry of Finance', loc: 'Malé',
    type: 'Full-time', dept: 'Legal',
    sal: 'MVR 18,000–25,000', salNote: '/mo + govt benefits', salVal: 25000,
    tags: ['Government', 'Administrative Law', 'Bilingual'], posted: '1d ago',
    desc: 'Provide legal advisory services to the Ministry, draft official correspondence, and support policy and regulatory implementation.',
    reqs: ['LLB or equivalent law degree', 'Maldivian national — required', 'Fluent Dhivehi and English', '2+ years legal experience preferred', 'Knowledge of Maldivian administrative law'],
  },
]

export const CATEGORIES = [
  { icon: '🍽️', name: 'Food & Beverage', count: 386 },
  { icon: '🛎️', name: 'Front Office', count: 214 },
  { icon: '⚙️', name: 'Engineering', count: 178 },
  { icon: '🛏️', name: 'Housekeeping', count: 264 },
  { icon: '💆', name: 'Spa & Wellness', count: 142 },
  { icon: '💼', name: 'Finance', count: 89 },
  { icon: '🤿', name: 'Diving & Water Sports', count: 98 },
  { icon: '📈', name: 'Sales & Marketing', count: 131 },
  { icon: '💻', name: 'IT & Technology', count: 56 },
  { icon: '👥', name: 'Human Resources', count: 73 },
  { icon: '🎨', name: 'Kids Club', count: 44 },
  { icon: '🐠', name: 'Marine Biology', count: 29 },
]

export const SALARIES = [
  { role: '🍽️ Head Chef (Resort)', range: 'USD 2,500–3,500' },
  { role: '🛎️ Front Office Manager', range: 'USD 2,000–3,000' },
  { role: '🤿 PADI Dive Instructor', range: 'USD 1,400–2,200' },
  { role: '💆 Spa Therapist', range: 'USD 1,200–1,900' },
  { role: '🛏️ Housekeeping Attendant', range: 'USD 700–1,100' },
  { role: '⚙️ Chief Engineer (Resort)', range: 'USD 2,800–4,000' },
  { role: '💼 Finance Manager (Local)', range: 'MVR 18,000–28,000' },
  { role: '💻 IT Systems Admin', range: 'MVR 14,000–22,000' },
  { role: '📈 Digital Marketing Exec', range: 'MVR 10,000–16,000' },
  { role: '🐠 Marine Biologist', range: 'USD 1,800–2,800' },
  { role: '🎨 Kids Club Coordinator', range: 'USD 1,200–1,800' },
  { role: '⚖️ Legal Officer (Govt)', range: 'MVR 18,000–25,000' },
]

export const EMPLOYERS = [
  { icon: '🏝️', name: 'Soneva Fushi', type: 'Eco-Luxury · Baa Atoll', open: 14 },
  { icon: '🌺', name: 'Four Seasons Maldives', type: 'Luxury Resort · Kuda Huraa', open: 9 },
  { icon: '⛵', name: 'Trans Maldivian Airways', type: 'Aviation · Malé', open: 6 },
  { icon: '🌊', name: 'Anantara Maldives', type: 'Resort Group · Multiple Atolls', open: 22 },
  { icon: '🌴', name: 'Six Senses Laamu', type: 'Eco-Luxury · Laamu Atoll', open: 8 },
  { icon: '🏦', name: 'Bank of Maldives', type: 'Finance · Malé', open: 5 },
  { icon: '🐡', name: 'Velaa Private Island', type: 'Ultra-Luxury · Noonu Atoll', open: 18 },
  { icon: '🌸', name: 'Atmosphere Hotels', type: 'Resort Group · Multiple', open: 31 },
]